import Head from 'next/head'
import 'tailwindcss/tailwind.css'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai'
import { MdEmail } from 'react-icons/md'
import Image from 'next/image'
import pfp from '/public/pfp.png'

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>claudia&apos;s portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-12 px-5 bg-four font-quicksand">
        <section className="h-screen">
          {/* <nav className="mb-1 flex justify-between">
            <h1 className=" text-lg">welcome :)</h1>
            <ul className=" flex items-center">
              <li><BsFillMoonStarsFill className=" cursor-pointer text-xl"/></li>
              <li>
                <a href="#" className=" text-sm px-5 py-2 bg-three rounded ml-5">resume</a>
                </li>
            </ul>
          </nav> */}
          <div className='relative mx-auto bg-five rounded-full w-80 h-80 overflow-hidden'>
            <Image src={pfp} alt="pfp" layout="fill" objectFit='cover'/>
          </div>
          <div className=" text-center p-5">
            <h2 className=" text-2xl font-bold md:text-4xl">claudia pereira carion</h2>
            <h3 className=" text-xl py-2 md:text-2xl">fullstack javascript developer</h3>
            <p className="pt-5 text-sm md:text-lg">originally from macau, currently living in stockholm.</p>
            <p className='text-sm md:text-lg'>educator turned developer with a passion for creativity.</p>
          </div>
          <div className='text-4xl flex justify-center gap-20 py-3 text-one'>
            <a href="https://www.linkedin.com/in/claudia-pereira-carion/"><AiFillLinkedin className='cursor-pointer'/></a>
            <a href="https://github.com/claudiacarion"><AiFillGithub className='cursor-pointer'/></a>
            <a href="mailto:claudia.carion@appliedtechnology.se"><MdEmail className='cursor-pointer'/></a>
          </div>
        </section>

        <section className="bg-three py-5 px-5 rounded-lg md:mx-12 lg:mx-24 ">
          <h2 className=" text-2xl font-bold text-center">projects</h2>
          <div className="flex justify-center gap-5 py-5">
            <div className="bg-five w-5/6 md:w-1/2 rounded-lg shadow-lg">
              <h3 className=" text-xl font-bold text-center py-5">project 1</h3>
              <p className=" text-center">description</p>
            </div>
            <div className="bg-five w-5/6 md:w-1/2 rounded-lg shadow-lg">
              <h3 className=" text-xl font-bold text-center py-5">project 2</h3>
              <p className=" text-center">description</p>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
